version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ../target:/usr/local/executable-jar:cached
    environment:
      - DATASOURCE_URL=jdbc:mysql://mysql:3306/usti?useSSL=false
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=usti
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - .mysql-data:/var/lib/mysql

